version: 2
jobs:
  build:
    docker:
      - image: nousdefions/circleci-lambda:latest

    steps:
      - checkout

      - run:
          name: update-npm
          command: npm install -g npm@latest

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Lint
          command: npm run lint 

      - run:
          name: Test 
          command: npm run test 
